Add GCC 8 as a native input to packages that depend on CUDA.
This works around the infamous:

  /gnu/store/…-cuda-toolkit-10.2.89/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
    138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
	|  ^~~~~

Regression introduced with Guix commit
6dffced09ecda024e0884e352778c221ad066fd6, which merged the branch
introducing GCC 10 as the default compiler.

Reported by Florent Pruvost.

* inria/tainted/hiepacs.scm (chameleon+cuda)[native-inputs]: New field.
(chameleon+cuda+mkl+mt)[native-inputs]: Likewise.
(pastix+cuda)[native-inputs]: Likewise.
* inria/tainted/storm.scm (starpu+cuda)[native-inputs]: Add GCC-8.